"""Ajout des tables

Revision ID: d99a056fcbb3
Revises: e613d02e5299
Create Date: 2025-07-04 01:48:34.297447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd99a056fcbb3'
down_revision = 'e613d02e5299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('nb_utilisations', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('boutique_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boutique_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commande_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plateforme', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('methode', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits_afrique.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits_afrique.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['vendeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendeur_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('boutique_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantite', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('montant_total', mysql.FLOAT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], name=op.f('vente_ibfk_1')),
    sa.ForeignKeyConstraint(['produit_id'], ['produits_afrique.id'], name=op.f('vente_ibfk_2')),
    sa.ForeignKeyConstraint(['vendeur_id'], ['vendeurs.id'], name=op.f('vente_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ventes')
    op.drop_table('product_views')
    op.drop_table('paiements')
    op.drop_table('order_shares')
    op.drop_table('commande_reviews')
    op.drop_table('boutique_visits')
    op.drop_table('boutique_views')
    op.drop_table('referral_links')
    op.drop_table('notifications')
    # ### end Alembic commands ###
