"""Initial migration

Revision ID: e613d02e5299
Revises: 
Create Date: 2025-06-29 22:45:07.352736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e613d02e5299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produits_alibaba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix_estime', sa.Float(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('min_commande', sa.Integer(), nullable=True),
    sa.Column('frais_livraison_estime', sa.Float(), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('vendeur', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('couleur', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe', sa.Text(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('client', 'vendeur', 'admin', name='userroleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe', sa.Text(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('boutiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendeur_id'], ['vendeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_commande', sa.Enum('afrique', 'alibaba', name='typecommandeenum'), nullable=False),
    sa.Column('date_commande', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes_groupees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_alibaba_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'cloturee', name='statutcommandeenum'), nullable=True),
    sa.Column('nb_utilisateurs', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('frais_partage_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['produit_alibaba_id'], ['produits_alibaba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('details_commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('type_produit', sa.Enum('afrique', 'alibaba', name='typeproduitenum'), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits_afrique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('pays_origine', sa.String(length=50), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('vendeur_id', sa.Integer(), nullable=True),
    sa.Column('boutique_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['vendeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('etat', sa.String(length=100), nullable=True),
    sa.Column('date_maj', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits_afrique.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['vendeurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente')
    op.drop_table('tracking')
    op.drop_table('produits_afrique')
    op.drop_table('details_commande')
    op.drop_table('commandes_groupees')
    op.drop_table('commandes')
    op.drop_table('boutiques')
    op.drop_table('vendeurs')
    op.drop_table('users')
    op.drop_table('produits_alibaba')
    # ### end Alembic commands ###
